name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SHOW_LINES_OF_CODE: true
          COMMIT_BY_ME: true
          SHOW_COMMIT: true
          SHOW_PROFILE_VIEWS: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_SHORT_INFO: true
          SHOW_LOC_CHART: true
